# Whether this GitHub repo is for a CC-led engineering project
engineering_project: true
# Name of the repository/project in English
english_name: CC Accidenz Commons
# All technologies used
technologies: font, OTF, UFO
# Whether this repository should be featured on the CC Open Source site's "Projects" page
featured: false
